version: '3.8'
services:
  postgres:
    image: postgres:16.0-alpine3.18
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1308werh
      - POSTGRES_DB=chat
    ports:
      - "127.0.0.1:5532:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/postgres.conf:/etc/postgresql/postgresql.conf
#      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 10s
      retries: 10
    logging:
      options:
        max-size: "200m"
